version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Choose either one of the orbs below
  # welcome: circleci/welcome-orb@0.4.1
  # aws-cli: circleci/aws-cli@2.0.3
# Define the jobs we want to run for this project
jobs:
  myjob1:  # Choose any name, such as `build`
      # The primary container, where your job's commands will run
      docker:
        - image: circleci/aws-cli@2.0.3
      steps:
        - checkout # check out the code in the project directory
        - run: echo "hello world" # run the `echo` command
  create_infrastructure:
    docker:
     - image: circleci/aws-cli@2.0.3
    steps:
     - checkout
     - run:
        name: Create CloudFormation Stack
        command: |
          aws cloud formation deploy --template-file template.yml --stack-name ${CIRCLE_WORKFLOW_ID:0:5} --region us-east-1
# Sequential workflow
workflows:
  # Name the workflow
  myWorkflow:
    jobs:
      - myjob1
      - create_infrastructure
